### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by AntoineLelaisant** [KnpLabs/bad-jokes#31]
# TODO

- [x] bootstrap a react native application runnable on expo
- [ ] Install the theme library (https://nativebase.io/)
- [ ] Setup redux & redux observable
